Add error checking for UTILS_VERSION and provide fallback default

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,7 +26,7 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.MINWARE_GITHUB_TOKEN }}
       run: |
-        LATEST_COMMIT=$(git ls-remote https://github.com/minwareco/minware-singer-utils.git refs/heads/main | cut -f1)
+        LATEST_COMMIT=$(git ls-remote https://$GITHUB_TOKEN@github.com/minwareco/minware-singer-utils.git refs/heads/main | cut -f1)
         echo "UTILS_VERSION=$LATEST_COMMIT" >> $GITHUB_ENV
         echo "Using minware-singer-utils version: $LATEST_COMMIT"
 
@@ -35,6 +35,11 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.MINWARE_GITHUB_TOKEN }}
         UTILS_VERSION: ${{ env.UTILS_VERSION }}
       run: |
+        if [ -z "$UTILS_VERSION" ]; then
+          echo "Error: UTILS_VERSION is not set"
+          exit 1
+        fi
+        echo "Installing with UTILS_VERSION=$UTILS_VERSION"
         python -m pip install --upgrade pip
         pip install -e .[dev]
         pip install pytest
